# Generated by Django 6.0.2 on 2026-02-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_color_car_status_car_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
