# Generated by Django 6.0.2 on 2026-02-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_car_likes_car_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=50),
        ),
    ]
