# Generated by Django 6.0.2 on 2026-02-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_car_fuel_type_alter_car_status_and_more'),
        ('cars', '0010_alter_car_columns'),
    ]

    operations = [
    ]
