# Generated by Django 6.0.2 on 2026-02-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_merge_20260228_0100'),
        ('cars', '0012_fix_column_length'),
    ]

    operations = [
    ]
