# Generated by Django 6.0.2 on 2026-02-28 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_merge_0011_merge_20260228_0100_0012_fix_column_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='car',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='car',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.PositiveIntegerField(choices=[(2, '2 Doors'), (4, '4 Doors')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine_size',
            field=models.DecimalField(decimal_places=1, default=1.6, help_text='Engine size in Liters (e.g. 1.8)', max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(choices=[(2, '2 Seats'), (4, '4 Seats'), (5, '5 Seats'), (6, '6 Seats'), (7, '7 Seats'), (8, '8 Seats')], default=1.6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.IntegerField(help_text='Car model or version'),
        ),
        migrations.AlterField(
            model_name='car',
            name='milage',
            field=models.IntegerField(help_text='Mileage in km/l'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('sold', 'Sold')], default='draft', max_length=50),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
        ),
    ]
