# Generated by Django 6.0.2 on 2026-02-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_remove_car_created_at_remove_car_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.DecimalField(decimal_places=1, default=1.6, help_text='Engine size in Liters (e.g. 1.8)', max_digits=4),
        ),
    ]
